# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '5.1.0.dev0+g0fbb009.d20230828'
__version_tuple__ = version_tuple = (5, 1, 0, 'dev0', 'g0fbb009.d20230828')
